version: '3'

services:
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wpdb
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - '8000:80'
    volumes:
      - './phpmyadmin/sessions:/sessions'
  php:
    build: ./php
    volumes:
      - ./app:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - '8080:80'
volumes:
  db:
